export const PRODUCT_REGISTER_REQUEST = 'PRODUCT_REGISTER_REQUEST';
export const PRODUCT_REGISTER_SUCCESS = 'PRODUCT_REGISTER_SUCCESS';
export const PRODUCT_REGISTER_FAIL = 'PRODUCT_REGISTER_FAIL';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';


export const LOGOUT_USER = 'LOGOUT_USER';